import { Inter } from "next/font/google"
import "./globals.css"
import NavBar from "@/components/navbar/NavBar"
import Footer from "@/components/footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Farm Merchanization",
  description: "Generated by Ajimerc",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " container"}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
